### ISSUE TITLE
Comparing a single object

### ISSUE THREAD

**Issue by rhiannonlynne** [testMOPS/mops#10]
Original orbit (Lynne)
S000qNg COM  0.682084069033000E+00  0.540590690499000E+00  0.272049780094600E+01  0.314400746000785E+03  0.256929800925527E+03  0.547705092835713E+05  0.237770000000000E+02  0.544660000000000E+05 1 6  0.484319537975270E-02 MOPS

Propagated (Lynne)
objid  q  e inc  node argPeri tPeri epoch H fluxnorm u_opp g_opp r_opp i_opp z_opp y_opp index n_par MOID COMPCODE g  objtype isvar t0 timescale sed_filename sedid
100392 0.681004270719 0.540328866013 2.64924729946 315.004630536 256.247924208 49500.4421939 49353.1606966 23.777 7.61834897599e-18 26.0803800326 24.5482551302 23.8981379286 23.6984281683 23.7527441087 23.7475446383 1 6 -1.0 OPENORB 0.15 0 0 NULL NULL S.dat 30001

Original orbit (Steve)
==> S0000qNga.orb <==
Object: S0000qNga
Solution: 1
QR= 0.682084069033 
EC= 0.540590690499 
IN= 2.720497800946 
OM= 314.400746000785 
W = 256.929800925527 
TP= 2454771.00928357133 
H= 23.777  G=0.15
EPOCH= 2454466.5

@ 50100.36672  comparison of position:
MOPS solution (RA, DEC, EPOCH)
141.711815307104 23.7960976997533 50100.36672

MafSSO Match (RA, DEC, EPOCH) with 49353 orbits
141.71230352 23.7957503538 50100.36672

Catsim match:  (objid epoch ra dec)
100392, 50100.3667199999982, 141.7111017749517, 23.7962236320797

Times of observations from Opsim: TAI (TAI-UTC  = 30 on this night)
Epochs for orbits should be TT.

**Comment by rhiannonlynne** [comment]
Command line oorb produces (somewhat painfully) ... in MJD_UTC
OpenOrb 
RA, Dec, Epoch
141.7331148743      23.7892157432   50100.3667202778

(full output @ closest time to 50100.36672 that I cared to get to)
S000qNg          807   50100.3667202778       0.0931690463     141.7331148743      23.7892157432      -0.0093937278       1.0784396579      -0.0905517069      19.7380809604      25.7424516166      18.8872154458     129.3620338121       9.7859246169       0.1692681899     159.3560831165     -14.1928853813       1.0715099604     119.1985504861       0.7198988991     136.5574085684       8.3179080224      18.9609104181       8.3188164164       1.6020523358       0.7208072931     117.5964981503      -0.0009083940      -0.5226815604       0.9352840938       0.0134627463      -0.0099268203      -0.0159214282      -0.0008574418      -0.4557464972       0.8718924324      -0.0000155979     300.8810487581     267.8500184776

If I play around with the python bindings, I can calculate ephemeris at this time in UTC as well - 
141.733114835 23.7892157556 50100.3667203
 .. so I think I'm pretty happy with that.

**Comment by rhiannonlynne** [comment]
And using the python bindings to oorb gets me 
RA      Dec    Epoch(MJD-TAI)
141.732705112 23.7892472724 50100.36672
(when I do this without doing any interpolation and using the 'original' orbit.)

And 
141.712224106 23.7957744747 50100.36672
(when I do the same thing without any interpolation but using the propagated-to-49353 version of the orbit)
(73" difference in RA, 23" difference in dec). 

and 
141.73270515 23.7892472605 50100.36672
if I use an orbit that was propagated at the command line to 50100.36 (TT). 
(this looks like: 
!!OID FORMAT q e i node argperi t_p H t_0 INDEX N_PAR MOID COMPCODE
S000qNg COM  0.681557544863371E+00  0.540368028676160E+00  0.268903671271691E+01  0.314716114505099E+03  0.256610066971003E+03  0.501599878973200E+05  0.237770000000000E+02  0.501003600000000E+05 1 6 -0.100000000000000E+01 OPENORB

I am so confused! 
It certainly looks like the version of the orbit I had which was propagated to 49353 is not good. 
If I redo that propagation (the propagated files we have are pretty old, and I imagine there may have been changes to oorb since then), I get: 
141.732705135 23.7892472651 50100.36672
and 
!!OID FORMAT q e i node argperi t_p H t_0 INDEX N_PAR MOID COMPCODE
S000qNg COM  0.681002932305742E+00  0.540327789764689E+00  0.264931490280015E+01  0.315004335154531E+03  0.256248293272237E+03  0.495004432031092E+05  0.237770000000000E+02  0.493530000000000E+05 1 6 -0.100000000000000E+01 OPENORB

So the newly propagated things are at least pretty self-consistent, but not consistent with your values (and not consistent with my old predictions based on the previously-propagated-to-49353 orbits). 

I'm not sure where to go next. Any suggestions @stevechesley?

**Comment by rhiannonlynne** [comment]
@pveres said he propagated and generated an ephemeris for this object at the 50100.36672 epoch (TAI) using JPL and using oorb and got different answers. 
Did propagation with JPL tools and with Oorb: in both case, generated the ephemeride using oorb. 
His comments:
1) I propagated orbit to the epoch of observation by using JPL tools and used oorb to generate ephemeris. The residuals are 0.12", 0.33" (JPL - oorb).
2) I propagated orbit to the epoch of observation by using oorb first and then calculated ephemeris by oorb.
Residuals are -76", 25" !!!

(we will compare oorb.conf file to check that these are the same between his/my configuration). 
I'd also like to know what the computed position was to compare to the values I found above.

**Comment by rhiannonlynne** [comment]
(wondering if I can tag @mgranvik here to see if he has any insight)

**Comment by stevechesley** [comment]
Certainly. It's all public anyway, and he may be able to quickly resolve the difficulty.

**Comment by rhiannonlynne** [comment]
@pveres calculated:
JPL (MOPS) = RA DEC EPOCH (mjd_UTC):
141.712224022272 23.7960664658642 50100.367067221996
141.7118153071 23.7960976998 50100.36672

OORB (propagated by JPL)
141.7121884745 23.7959724684 50100.367067222
141.7117797625 23.7960037043 50100.36672

OORB (propagated by oorb)
141.7335240091 23.7891842477 50100.367067222
141.7331145152 23.7892157784 50100.36672

By the way, when running oorb, I use --start-mjd-utc option for ephemeris and for propagation --epoch-mjd-tt. But, even when times (UTC, TT, TAI) are somehow confused, I should not have a such a huge difference in RA and DEC.

**Comment by rhiannonlynne** [comment]
My oorb.conf (as a txt file)
[oorb_conf.txt](https://github.com/testMOPS/mops/files/4662/oorb_conf.txt)

**Comment by rhiannonlynne** [comment]
Yes - that's quite a difference between the propagated by JPL vs the propagated by Oorb positions! 
I got positions that look very similar to yours when using oorb alone.
Lynne's (all oorb): (UTC-MJD)
141.733114835 23.7892157556 50100.3667203
Peter's (prop by oorb):
141.7331145152 23.7892157784 50100.36672

which, as you say, are very different to the propagated by JPL positions. 
(oorb with JPL-propagated orbit)
141.7117797625 23.7960037043 50100.36672
(pure JPL propagated and ephemeris generation)
141.7118153071 23.7960976998 50100.36672

Do you want to paste in the orbital information, as propagated by JPL and as propagated by OORB? 
I'd like to pass this along to Mikael and see if he has anything to add. 
It is starting to look like something is wrong with the oorb propagations.

**Comment by pveres** [comment]
Sure, this is what I have:

input orbit from SSM:
S0000qNga COM 0.682084069033 0.540590690499 2.720497800946 314.400746000785 256.929800925527 54770.509283571329 23.777000000000 54466.000000000000 1 6 -1 MOPS

propagation by MOPS::
S0000qNga COM 0.681558387064 0.540368781325 2.688998140657 314.716212833896 256.609783556000 50159.989634815436 23.777000000000 50100.366719999998 1 6 -1 MOPS

propagation by oorb by using Lynne's oorb.conf:
S0000qNga COM  0.681557513164044E+00  0.540368061834731E+00  0.268903705418636E+01  0.314716112481577E+03  0.256610071457733E+03  0.501599878963795E+05  0.237770000000000E+02  0.501003667200000E+05 1 6 -0.100000000000000E+01 OPENORB

ephemeris (oorb's propagated orbit)
141.7117797631  23.7960037041

ephemeris (MOPS propagated orbit)
141.7331145507  23.7892157671

 ... (comment by Lynne - are these positions reversed above? I thought the MOPS positions were 141.71\* while the Oorb stuff was 141.73\* ? )

**Comment by pveres** [comment]
Note, that the orbit was propagated for almost 12 years....

**Comment by mgranvik** [comment]
Which observatory code are these ephemerides referring to? Geocenter (ie 500)?

**Comment by pveres** [comment]
--code=807

**Comment by mgranvik** [comment]
I suspect that the problem is in the conversion from cometary elements to 
cartesian elements.

First I downloaded a current cartesian state vector for Ceres from Horizons:

1 CAR 2.043479626618516E+00 -2.102801223725915E+00 -4.427780809553923E-01 
6.922831268434070E-03 6.603571403904928E-03 -1.068633337376089E-03 3.34 57294.0 
1 6 -1 HORIZONS

Integrating to from MJD 57294 TT to MJD 57294 UTC (a minute or so):

1 CAR  0.204348508987898E+01 -0.210279601240004E+01 -0.442778924283638E+00 
0.692281297044631E-02  0.660359023317927E-02 -0.106862937195156E-02 
0.334000000000000E+01       0.5729400079E+05 1 6 -0.100000000000000E+01 OPENORB

oorb ephemeris for MJD 57294 UTC for 500:

299.6319956600  -31.1741104367

Horizons ephemeris for MJD 57294 UTC for 500:

299.63200 -31.17412

**\* Ephemeris calculation is ~okay ***

Next I downloaded a cartesian state vector for Ceres from Horizons for a date 
15 years earlier:

1 CAR -1.802088780568611E+00 -1.974960060344324E+00 2.711256779646021E-01 
7.114199867873460E-03 -7.763860220236919E-03 -1.550693223382579E-03 3.34 51816.0 
1 6 -1 HORIZONS

Integrating to MJD 57294 UTC:

1 CAR  0.204348479032744E+01 -0.210279646250204E+01 -0.442778883978354E+00 
0.692281394266230E-02  0.660358880020891E-02 -0.106862965277622E-02 
0.334000000000000E+01       0.5729400079E+05 1 6 -0.100000000000000E+01 OPENORB

Ephemeris for MJD 57294 UTC for 500:

299.6319828608     -31.1741105571

***\* 15-year integration + ephemeris calculation is good to a fraction of an arcsec ****

So the only difference is the conversion from cometary elements to cartesian.

If you ask me I don't see any reason to use cometary elements in an automated 
pipeline. For visualization I understand the need, but otherwise I would make 
life simple and use cartesian elements only.

Mikael

**Comment by rhiannonlynne** [comment]
What we have as our inputs are cometary orbits (from the PSMOPS model). 
@stevechesley @pveres does JPL have some code that could be made available to do this conversion? Presumably, once we had a cartesian version of the elements, I could still pop those into oorb and the rest of the software would work with just small modifications.

**Comment by stevechesley** [comment]
I'm not following all of the numbers flying around. We need to talk with respect to some reference RA-DEC value, rather than giving the RA-DEC itself which has not much value. Can we difference the numbers against the MOPS solution [(RA, DEC, EPOCH) =141.711815307104 23.7960976997533 50100.36672]?

@mgranvik, I have a hard time believing that oorb is not able to get back and forth between cartesian and comet elements accurately. Is that what you are saying?

**Comment by rhiannonlynne** [comment]
Okay guys - I have done some tests and I'd like you  (the experts) to have a look.
It really doesn't seem to me that oorb has a problem with propagating, even with cometary orbits. 
Please see the file "test_orb" (in the repo https://github.com/testMOPS/mops/blob/master/test_orb) for some details on a comparison for a PHA between Horizons and Oorb predictions. 
Please let me know if there's anything unexpected there. 

I couldn't figure out how to get oorb to accept cartesian coordinates for input, so I did not test the cartesian coordinates. It doesn't look (to me anyway) as if it is necessary. 

If there are no problems in my analysis, where do we go next? Is it possible for you to double check the propagation and ephemeris predictions of the code you're using (presumably outside the horizons system) for this same object? Could there be any problems there? If not - any other ideas? 

Also, can I just make a complaint as a user of all these different systems -- it kind of sucks that everyone has different conventions and no translation tools. There are a few snippets of python that might help in the repo now, but they're certainly not comprehensive. 
Also - nobody agrees with the MPC. Is this because of the level of significant figures reported for their orbits? Or is it something else?

**Comment by rhiannonlynne** [comment]
@pveres @stevechesley @mgranvik precession, nutation, and aberration: are these effects included in the ephemeris predictions for Horizons and OpenOrb?

My conclusion from a quick test (since Horizons gives you the option to add aberration, precession, nutation and optionally refraction) is that oorb provides ICRS/ICRF coordinates.

**Comment by stevechesley** [comment]
RA-DEC positions are measured/computed relative to a star catalog, which has the inertial (unaberrated) positions of the stars in the J2000 frame. So no precession, nutation or aberration are included in the reported RA-DEC positions. But to compute the position of the observer (to get residuals) a precession/nutation model for Earth is required, though this is only important for nearby objects (less than 0.01 au, say). Refraction appears nowhere in the process.

**Comment by rhiannonlynne** [comment]
STARTING ANEW! 

'original orbit'
S000qNg COM 0.682084069033000E+00 0.540590690499000E+00 0.272049780094600E+01 0.314400746000785E+03 0.256929800925527E+03 0.547705092835713E+05 0.237770000000000E+02 0.544660000000000E+05 1 6 0.484319537975270E-02 MOPS

translation from the JPL database version (with correct epoch)
!!OID FORMAT q e i node argperi t_p H t_0 INDEX N_PAR MOID COMPCODE
test COM 0.682084069033 0.540590690499 2.720497800946 314.400746000785 256.929800925527 54770.509283572 10.000000 54466.000000000 1 6 1 HORIZONS

JPL database version:
Object: S0000qNga
Solution: 1
QR= 0.682084069033 
EC= 0.540590690499 
IN= 2.720497800946 
OM= 314.400746000785 
W = 256.929800925527 
TP= 2454771.00928357133 
H= 23.777 G=0.15
EPOCH= 2454466.5

Prediction position on: 
@ 50100.36672 (MJD UTC)
@ 2450100.866720 (JD UTC)

**Comment by rhiannonlynne** [comment]
Using python binding to oorb:

MJD(UTC)    RA    Dec   Delta
50100.36672 141.733114605 23.7892157499 0.0931690488937

**Comment by rhiannonlynne** [comment]
(same problem - Steve recreates same 17.711 position). 

141.711815307104 23.7960976997533 50100.36672

Change date to epoch: 

2454466.5 UTC JD
54466.000000 (UTC MJD)

and obscode to 500

Then: 
MJD(UTC)    RA    Dec   Delta
54466.0 8.66741514291 7.01182722282 2.03840584663

**Comment by stevechesley** [comment]
*****************\*  EPHGEN v3.5-ifort  2015-Oct-27 16:52:53  ******************
 **\*  Object:   S0000qNga
 **\*  Ref Solution: 1  
0******\* Inputs to EPHGEN:
 PEFILE = mops_data/pleph.nio
 SBFILE = mops_data/sbeph.nio
 PGSIZE = 1000000000
 SBPERT = T
 EMSEP =  T
 G =      0.15
 TOL =    1e-15
 EOBL_LIM = 10.0
 OBSCOD = 500
 TSTRT =  2454466.5
 TSTOP =  2454467
 TSTEP =  10d
 FORM =   CD, RADEC_DEG:12, RADECR, RE, SOE, SEO, MAG
 QR =     0.682084069033
 EC =     0.540590690499
 IN =     2.720497800946
 OM =     314.400746000785
 W =      256.929800925527
 TP =     2454771.00928357133
 H =      23.777
 EPOCH =  2454466.5
0******\*  Perturbing Bodies:
   Planetary Ephemeris: DE405
  Small-Body Ephemeris: SB405-CPV-2
0Initial coordinates to integrator at T= 2454466.00000
     1.834923762387719E+00  1.191240659527653E+00  6.330935949976321E-01
    -5.205042559989965E-03  5.301032786508190E-03  2.315292197303249E-03
1
                        Geocentric Ephemeris for S0000qNga : Orbit Ref. JPL#1
       Date                       J2000                      Rates
        UT                R.A.             Dec.          R.A.     Dec.      rE    S-O-E  S-E-O   Vm
 YYYY-mmm-DD HH:MM  ddd.dddddddddddd +dd.dddddddddddd      arcsec/h         AU     deg    deg   mag

---

 2008-Jan-01 00:00    8.667411532802 +07.011832720736    25.849    7.900   2.038   25.6   90.9  28.3

(compare 
MJD(UTC) RA Dec Delta
54466.0 8.66741514291 7.01182722282 2.03840584663)

**Comment by rhiannonlynne** [comment]
Delta: 0.01" RA ,  0.02" Dec

corresponds to about a 1 second difference in time (or 30 km in distance)

**Comment by rhiannonlynne** [comment]
Looking into orbit conversion:

ewok:~/otherRepos/testMOPS/mops] lynnej% more tjpl.des
!!OID FORMAT q e i node argperi t_p H t_0 INDEX N_PAR MOID COMPCODE
test COM 0.682084069033 0.540590690499 2.720497800946 314.400746000785 256.929800925527 54770.509283572 10.000000 54466.000000000 1 6 1 HORIZONS

[ewok:~/otherRepos/testMOPS/mops] lynnej% more tjpl2.des
!!OID FORMAT x y z dx/dt dy/dt dz/dt H t_0 INDEX N_PAR MOID COMPCODE
test CAR  0.183231549710134E+01  0.134766017860745E+01  0.107011164951865E+00 -0.522801513289551E-02  0.576770860165269E-02  0.142685868984292E-04  0.100000000000000E+02       0.5446600000E+05 1 6 -0.100000000000000E+01 OPENORB

[ewok:~/otherRepos/testMOPS/mops] lynnej% more tjpl3.des
!!OID FORMAT q e i node argperi t_p H t_0 INDEX N_PAR MOID COMPCODE
test COM  0.682084069033000E+00  0.540590690498999E+00  0.272049780094586E+01  0.314400746000789E+03  0.256929800925524E+03  0.547705092835721E+05  0.100000000000000E+02       0.5446600000E+05 1 6 -0.100000000000000E+01 OPENORB

[ewok:~/otherRepos/testMOPS/mops] lynnej% more tjpl4.des
!!OID FORMAT x y z dx/dt dy/dt dz/dt H t_0 INDEX N_PAR MOID COMPCODE
test CAR  0.183231549710186E+01  0.134766017860688E+01  0.107011164951857E+00 -0.522801513289090E-02  0.576770860165606E-02  0.142685868987226E-04  0.100000000000000E+02       0.5446600000E+05 1 6 -0.100000000000000E+01 OPENORB

**Comment by rhiannonlynne** [comment]
Using original tjpl.des orbit: 

#Designation MJD_UTC/UT1 RA Dec dRA/dt dDec/dt VMag Delta dDelta/dt
test 54465.9992455556 8.6672841635 7.0117874800 0.1723231827 0.0526835325 14.5037554281 2.0383957293 0.0134099583

Using tjpl2.des (the cartesian version)
#Designation MJD_UTC/UT1 RA Dec dRA/dt dDec/dt VMag Delta dDelta/dt
test 54465.9992455556 8.6672841635 7.0117874800 0.1723231827 0.0526835325 14.5037554281 2.0383957293 0.0134099583

MJD(UTC) RA Dec Delta
54466.0 8.66741514291 7.01182722282 2.03840584663)
MJD(UTC)    RA    Dec   Delta
54465.9992456 8.66728416351 7.01178747999 2.03839572933

(in the 65 seconds between UT and TT, object moved about .5").

**Comment by rhiannonlynne** [comment]
Attempt to investigate source of 30km discrepancy in ephemeris between JPL and Oorb @ epoch of orbit, obscode=500. 

1 - check epoch and orbital elements. 
  done: and, cartesian/cometary elements in oorb go round-trip with less than this amount of error

2 - check state @ epoch (cartesian elements at epoch)
  done: cartesian xyz match to within 0.5 m

3 - check emit xyz of object

**Comment by rhiannonlynne** [comment]
Checking state at epoch from OORB:

[ewok:~/otherRepos/testMOPS/mops] lynnej% more tjpl2.des
!!OID FORMAT x y z dx/dt dy/dt dz/dt H t_0 INDEX N_PAR MOID COMPCODE
test CAR 0.183231549710134E+01 0.134766017860745E+01 0.107011164951865E+00 -0.522801513289551E-02 0.576770860165269E-02 0.142685868984292E-04 0.100000000000000E+02 0.5446600000E+05 1 6 -0.100000000000000E+01 OPENORB

--- this is the xyz position and velocity _at_ the epoch time (but light travel time is not included, so this is where the object is in space but not where/when we will see it)

[ewok:~/otherRepos/testMOPS/mops] lynnej% oorb --task=ephemeris --orb-in=tjpl.des --obsCode=500 | awk '{print $3, $5, $6, $4, $29, $30, $31, $32, $33, $34, $35, $36, $37}'
MJD_UTC/UT1 RA Dec Delta HEclObj_X HEclObj_Y HEclObj_Z HEclObj_dX/dt HEclObj_dY/dt HEclObj_dZ/dt HEclObsy_X HEclObsy_Y HEclObsy_Z
54465.9992455556 8.6672841635 7.0117874800 2.0383957293 1.8323770423 1.3475922742 0.1070109968 -0.0052274745 0.0057681062 0.0000143002 -0.1676694568 0.9688884731 -0.0000150849

-- this xyz position and velocity are where the object is when we see it at this time (so, essentially, 17 minutes earlier than above due to light travel) .. the velocity give an offset of about the right value (order of magnitude .. still differences, on the order of 0.3% due to velocity changing and needing to iterate on light-travel time offsets)

**Comment by stevechesley** [comment]
JPL state @ epoch (cartesian elements)

 MJD                          Heliocentric Position                                                 Heliocentric Velocity
  ET              X                      Y                      Z                       dX                     dY                     dZ
                                         AU                                                                   AU/d

---

 54466 +1.832315497097837E+00 +1.347660178611321E+00 +1.070111649518741E-01  -5.228015132926363E-03 +5.767708601629984E-03 +1.426858689662654E-05

-- Good, this matches the oorb state @ epoch to about 0.5 meters.

**Comment by stevechesley** [comment]
```
                                                              Geocentric Ephemeris for S0000qNga : Orbit Ref. JPL#1
   Date                       J2000                      Rates                                                       Heliocentric Position
    ET                R.A.             Dec.          R.A.     Dec.              rE                      X                      Y                      Z             S-O-E  S-E-O   Vm
```

 YYYY-mmm-DD HH:MM  ddd.dddddddddddd +dd.dddddddddddd      arcsec/h                 AU                                             AU                                    deg    deg   mag

---

 2008-Jan-01 00:00    8.667280561412 +07.011792980350    25.848    7.900  +2.038395810534400E+00  +1.832315497097843E+00 +1.347660178611314E+00 +1.070111649518743E-01   25.6   90.9  28.3

**Comment by stevechesley** [comment]
Detailed outputs, states in EME2000. Next post will have in J2000 Ecliptic.

From integrator:
 ET_INI: 2454466.00000
 X_INI:    1.834923762387725E+00  1.191240659527646E+00  6.330935949976292E-01
 V_INI:   -5.205042559989909E-03  5.301032786508228E-03  2.315292197303268E-03

The rest at requested ephemeris time:
ET, UT:    8466.00000000000        8465.99924560185     

Geometric state (at rec. time?)
 X_OBJ:    1.83231549709784        1.19388744279331       0.634249257295174  
 V_OBJ:  -5.228015132926310E-003  5.286093463322766E-003  2.307353896329159E-003

Emit state:
 X_EMI:    1.83237704225196        1.19382520863916       0.634222092195324  
 V_EMI:  -5.227474469249435E-003  5.286445688502601E-003  2.307541021934342E-003

Earth at rec. time
 X_EAR:  -0.167669456756887       0.888943861886400       0.385387705962524  
 V_EAR:  -1.723508180828711E-002 -2.745473554689948E-003 -1.189750240645492E-003

Observer at rec. time (same as Earth here):
X_OBS:  -0.167669456756887       0.888943861886400       0.385387705962524  
 V_OBS:  -1.723508180828711E-002 -2.745473554689948E-003 -1.189750240645492E-003

Relative position (for RA-DEC computation);
 R_OBJ_OBS:    2.00004657423389       0.304881340251077       0.248834382001733

**Comment by stevechesley** [comment]
Now in Ecliptic frame:

 X_INI:          1.83492376238773          1.34477210638094         0.107003695443852
 V_INI:       -0.00520504255998991       0.00578457283745656      1.56093141554185e-05
 X_OBJ:           1.83231549709784          1.34766017861131         0.107011164951875
 V_OBJ:       -0.00522801513292631       0.00576770860163003      1.42685868966285e-05
 X_EMI:           1.83237704225196          1.34759227423507         0.107010996784888
 V_EMI:       -0.00522747446924943       0.00576810619620537      1.43001641524552e-05
 X_EAR:         -0.167669456756887         0.968888473076174     -1.52540016960523e-05
 V_EAR:        -0.0172350818082871      -0.00299217820530661       5.1215813611752e-07
 X_OBS:         -0.167669456756887         0.968888473076174     -1.52540016960523e-05
 V_OBS:        -0.0172350818082871      -0.00299217820530661       5.1215813611752e-07
 R_OBJ:           2.00004657423389         0.378703793510699         0.107026249490877

**Comment by rhiannonlynne** [comment]
Steve looked at differences -- emit states < 10m difference, but the position of the earth is 25 km (!) out of place in the z direction. 

(z = -25.297)

**Comment by stevechesley** [comment]
LSST Prediction at 1996-Jan-18 08:48 for code 807:

T_INI= 2450100.36672
X_INI        -0.517682378128683         0.943248570273295        0.0138926673375748
V_INI      -0.00998928226996381        -0.015808708337284     -0.000855782305461691

 ET, UT:    50100.3674396757        50100.3667199998  
X_OBJ         -0.52266867184861         0.935304708306426        0.0134637474765193
V_OBJ      -0.00992699408359701       -0.0159211488345263     -0.000857426265364538
X_EMI        -0.522663329718481         0.935313276079784        0.0134642088913595
V_EMI       -0.0099270617751788       -0.0159210277351197     -0.000857424514590214
X_EAR        -0.455709608010423          0.87189992496842      4.24882940514015e-06
V_EAR       -0.0155359863515486      -0.00803366185969467     -3.62566342809734e-07
X_OBS          -0.4557464890272         0.871892436677645     -1.57456761292751e-05
V_OBS       -0.0155428095495517      -0.00824690074520342      9.20848940911051e-05
R_OBS       -0.0669168367280867        0.0634208404611714        0.0134799544634611

R_OBS is the aberrated position of the obect with respect to the observer

**Comment by rhiannonlynne** [comment]
Comparison for 807 on  1996 date:

oorb --task=propagation --orb-in=tjpl.des --epoch-mjd-tt=50100.3674396757 --conf=oorb.conf --orb-out=tjpl_96.des
[ewok:~/otherRepos/testMOPS/mops] lynnej% oorb --task=ephemeris --orb-in=tjpl_96.des --code=807 | awk '{print $3, $5, $6, $4, $29, $30, $31, $32, $33, $34, $35, $36, $37}'
MJD_UTC/UT1 RA Dec Delta HEclObj_X HEclObj_Y HEclObj_Z HEclObj_dX/dt HEclObj_dY/dt HEclObj_dZ/dt HEclObsy_X HEclObsy_Y HEclObsy_Z
50100.3667202778 141.7331149446 23.7892157209 0.0931690463 -0.5226815605 0.9352840937 0.0134627463 -0.0099268203 -0.0159214282 -0.0008574418 -0.4557464972 0.8718924324 -0.0000155979

Earth still off by about 22km in z: 

> > > (oorb_obs - jpl_obs) \* au2m / 1000.
> > > array([ -1.22265088,  -0.63993569,  22.10730894])

but now the emitter location is also off by a large amount. 

> > > (oorb_xyz - jpl_xyz) \* au2m / 1000.
> > > array([-2727.32491525, -4365.68401569,  -218.80366738])

Also, let's try this using the cartesian coordinates just in case:
 oorb --task=propagation --orb-in=tjpl2.des --epoch-mjd-tt=50100.3674396757 --conf=oorb.conf --orb-out=tjpl_c_96.des
oorb --task=ephemeris --orb-in=tjpl_c_96.des --code=807 | awk '{print $3, $5, $6, $4, $29, $30, $31, $32, $33, $34, $35, $36, $37}'
MJD_UTC/UT1 RA Dec Delta HEclObj_X HEclObj_Y HEclObj_Z HEclObj_dX/dt HEclObj_dY/dt HEclObj_dZ/dt HEclObsy_X HEclObsy_Y HEclObsy_Z
50100.3667202778 141.7331111635 23.7892169364 0.0931690475 -0.5226815572 0.9352840989 0.0134627466 -0.0099268203 -0.0159214281 -0.0008574418 -0.4557464972 0.8718924324 -0.0000155979

**Comment by rhiannonlynne** [comment]
After updates to oorb, we can now match on this object to sub-milliarcsecond precision. 
(see issue 17 in oorb: https://github.com/oorb/oorb/issues/17)
