### ISSUE TITLE
make sure our orbits match

### ISSUE THREAD

**Issue by rhiannonlynne** [testMOPS/mops#11]
@pveres  
can you put a copy of the orbit database you're using somewhere i can download it? 
i thought we were just using a the same, standard S3M .. but I'm finding that some of the objects you have listed in n747_dets_new.txt are not in my NEO population. Specifically, I don't have any records for 
['S0000aU3a' 'S00003tTa' 'S000084qa' 'S0000WwGa']

So this makes me worry that perhaps the rest of our orbits might be slightly different.

**Comment by pveres** [comment]
Here is the file with orbits. It contains above mentioned records:
@rhiannonlynne  
[S0.zip](https://github.com/testMOPS/mops/files/92288/S0.zip)

**Comment by rhiannonlynne** [comment]
That's so odd. There are about 300 more objects here that weren't in the other file, yet both are supposed to be S3M, S0. Assuming the version at the top of your file refers to the date, they are about 2 years apart in generation. Swapped in your version.
