### ISSUE TITLE
Which JPL ephemeris to use for comparison?

### ISSUE THREAD

**Issue by rhiannonlynne** [testMOPS/mops#12]
Since we will be switching to an entirely new baseline run, and this means we at UW have to regenerate our database (which we did anyway, due to the errors in oorb) we can revisit the JPL ephemeris we should use. 

We had previously decided to both use DE405 for the existing comparison (and I will continue to use this for the n747 single night comparison). 
But as we move toward building the full month comparison and longer 10 year comparisons, should we actually be using DE430? Whatever we use will be what becomes 'baked into' our database. 
Note that Oorb still does not include asteroid perturbations, so we still can't turn those on for detailed comparisons. 

@stevechesley @pveres

**Comment by stevechesley** [comment]
Our plan has been to stick with DE405 for the duration of the study and neglect asteroid perturbers. (Peter, please verify the latter is still set on arjuna2.)

You'll want to switch to DE430 for processing real data, but you'll also need asteroid perturbers then, too, so there is no reason to make the switch until oorb can handle asteroid perturbers.

**Comment by pveres** [comment]
I confirm arjuna2 MOPS uses DE405 as an ephemeris.

Peter

On Sun, Jan 17, 2016 at 10:20 PM, Steve Chesley notifications@github.com
wrote:

> Our plan has been to stick with DE405 for the duration of the study and
> neglect asteroid perturbers. (Peter, please verify the latter is still set
> on arjuna2.)
> 
> You'll want to switch to DE430 for processing real data, but you'll also
> need asteroid perturbers then, too, so there is no reason to make the
> switch until oorb can handle asteroid perturbers.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/testMOPS/mops/issues/12#issuecomment-172437985.

## 

Peter Veres
Caltech Postdoctoral Scholar

Jet Propulsion Laboratory, NASA
Mission Design & Navigation
T1721-202
4800 Oak Grove Dr.
Pasadena, CA 91109

http://scienceandtechnology.jpl.nasa.gov/people/P_Veres/
phone: 818-354-0919
email: veres@jpl.nasa.gov

**Comment by stevechesley** [comment]
And what about the asteroid perturbers? SBPERT=F everywhere?

**Comment by pveres** [comment]
Yes, perturbing small bodies are turned off (through switch
use_small_bodies).

Peter

On Mon, Jan 18, 2016 at 1:54 AM, Steve Chesley notifications@github.com
wrote:

> And what about the asteroid perturbers? SBPERT=F everywhere?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/testMOPS/mops/issues/12#issuecomment-172482176.

## 

Peter Veres
Caltech Postdoctoral Scholar

Jet Propulsion Laboratory, NASA
Mission Design & Navigation
T1721-202
4800 Oak Grove Dr.
Pasadena, CA 91109

http://scienceandtechnology.jpl.nasa.gov/people/P_Veres/
phone: 818-354-0919
email: veres@jpl.nasa.gov
