### ISSUE TITLE
Compare initial n747 detections.

### ISSUE THREAD

**Issue by rhiannonlynne** [testMOPS/mops#6]
On the LSST side, I want to compare n747 detections generated using MafSSO (already in the repo, n747 directory) with detections generated from the CatSim database (TBD).

**Comment by pveres** [comment]
I provided n474 detections (file) for comparison.

**Comment by rhiannonlynne** [comment]
Thanks Peter. I'm stuck deep in a round of opsim evaluations looking at our max completeness if we change the survey strategy that have some urgency at the moment (not ignoring this on purpose!).

**Comment by pveres** [comment]
@rhiannonlynne 
Two files (obscode 807 and 500). Previously, I used wrong UTC (in fact, I need to subtract 30 seconds for night 747 to get UTC from TAI epochs that are in enigma databases).

I applied filtered as if all asteroids are S types.
Also, trailing losses are applied (red curve). Files are tab separated. Original epoch is epoch_mjd+30 seconds (TAI). Circular FOV 9.6211275016 square degrees. Fill factor is 100%, fading is on.

[807_nn747.txt](https://github.com/testMOPS/mops/files/98526/807_nn747.txt)
[500_nn747.txt](https://github.com/testMOPS/mops/files/98525/500_nn747.txt)

**Comment by rhiannonlynne** [comment]
@pveres thanks for the updates -- can you please add the magnitudes to these files?

**Comment by rhiannonlynne** [comment]
I am SUPER happy to report than now ra/dec values match to within: 
ra/dec difference rms (arcsec) 0.00127971177477 0.000409896788474
ra difference min/max (arcsec) -0.0117189044772 0.01727504565
dec difference min/max (arcsec) -0.00544591392782 0.00330842643681

I think this is reasonable, but please let me know if there are still concerns.
The biggest offsets (that 0.017") occur when there is a very close NEO.

**Comment by pveres** [comment]
@rhiannonlynne 
Same files with magnitudes. Note that the number of lines is not exactly the same as in the previous files because of applied fading (which has random numbers involved).
[807_nn747.txt](https://github.com/testMOPS/mops/files/99672/807_nn747.txt)
[500_nn747.txt](https://github.com/testMOPS/mops/files/99671/500_nn747.txt)

**Comment by pveres** [comment]
That's great news, these offsets are tiny in comparison with those
previous...

I uploaded night747 with magnitudes to the existing issue.

Peter

On Thu, Jan 21, 2016 at 9:51 AM, Lynne Jones notifications@github.com
wrote:

> I am SUPER happy to report than now ra/dec values match to within:
> ra/dec difference rms (arcsec) 0.00127971177477 0.000409896788474
> ra difference min/max (arcsec) -0.0117189044772 0.01727504565
> dec difference min/max (arcsec) -0.00544591392782 0.00330842643681
> 
> I think this is reasonable, but please let me know if there are still
> concerns.
> The biggest offsets (that 0.017") occur when there is a very close NEO.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/testMOPS/mops/issues/6#issuecomment-173652371.

## 

Peter Veres
Caltech Postdoctoral Scholar

Jet Propulsion Laboratory, NASA
Mission Design & Navigation
T1721-202
4800 Oak Grove Dr.
Pasadena, CA 91109

http://scienceandtechnology.jpl.nasa.gov/people/P_Veres/
phone: 818-354-0919
email: veres@jpl.nasa.gov

**Comment by rhiannonlynne** [comment]
![figure_1](https://cloud.githubusercontent.com/assets/1855711/12491928/8789d026-c032-11e5-811a-0318e94e807f.png)

RA/Dec residuals

**Comment by rhiannonlynne** [comment]
![figure_6](https://cloud.githubusercontent.com/assets/1855711/12491948/a580d340-c032-11e5-9140-bb24711bf939.png)
Mag residuals a little bigger, but overall not too bad .. 
ra/dec difference rms (arcsec) 0.00127781501836 0.000411827822456
ra difference min/max (arcsec) -0.0117189042214 0.0172750476963
dec difference min/max (arcsec) -0.00544591318601 0.00330842642722
Vmag difference min/max -0.0347946314025 0.0161321148771

**Comment by pveres** [comment]
The offsets are indeed negligible in both astrometry and photometry (majority of them).
