### ISSUE TITLE
False detections

### ISSUE THREAD

**Issue by pveres** [testMOPS/mops#8]
@mjuric @ivezic @rhiannonlynne @stevechesley 
I see that there are 500-600 false detections per camera footprint following Kaiser's equation at S/N>5. Is that right?

See attached plot.

I used 3,2 billion pixels, sigma from seeing=1.2 or 0.8" (sigma=seeing/2.35) and 0.20" pixels.

![false_dets_lsstcam](https://cloud.githubusercontent.com/assets/13923689/9776257/7705710a-570b-11e5-832a-f35b608b8ac8.png)

**Comment by ivezic** [comment]
The number I remember is 6-8 per CCD (estimates vary, don't know why, could
be seeing assumptions), so about 1100-1500 per focal plane, or twice as many
as your estimate (practically all have SNR<6). 
Btw, I didn't quite understand this line:

> I used 3,2 billion pixels, sigma from seeing=1.2 or 0.8" (sigma=seeing/2.35) and 0.20" pixels.
> can you please provide more detail?

**Comment by mjuric** [comment]
@pveres I think it's more than that -- see Table 3 in https://github.com/lsst/W13report/blob/master/W13report_V1-02.pdf.

For SNR=5 and good (FWHM=0.6) seeing, it's ~12/chip, and for FWHM=0.88 seeing it's 5. I think Becker confirmed this against the raytraced simulation (see Figure 4). He's also used the Kaiser analysis to get the analytic estimate, so I'm not sure where the discrepancy comes from (maybe something in the assumptions?).

**Comment by stevechesley** [comment]
So the question is what is sigma_g in Becker et al. Eq. 3? I can't seem to put my hands on the Kaiser 2004 report. 

I can match the table 3 results if I use sigma_g = FWHM/2.35/sqrt(2), where FWHM is in pixels. I believe Peter is using sigma_g = FWHM/2.35, which I gather is based on PS-MOPS scripts. So the difference is a simple factor of 2.

**Comment by stevechesley** [comment]
So Larry sent us the Kaiser doc. It's quite long, but it seems the relevant eqs. are 149 and 153, and they seem to support the approach Peter has taken, which gives half of the density from Becker's Table 3.

**Comment by ivezic** [comment]
Could this factor of 2 discrepancy be due to Becker counting both positive and
negative excursions/detections? See his comment after eq. 3 in the report. 
        Z.

**Comment by mjuric** [comment]
I think it's accounting for negative deviations as well as positive, as @ivezic says.

PS: @ivezic, I did get your comments via e-mail.

**Comment by stevechesley** [comment]
OK, I think this all makes sense. I note that Becker's Fig. 3 says this is the density of _peaks_, when it is actually _peaks and valleys_ since the curve seems to match what is in Table 3. But everything seems to hang together and Peter's 500-600 per field matches with the 5+/-2  (more precisely 5.49) in the table: 5.49/2 \* 200 chips = 549 **positive** noise sources per visit for 0.88" seeing. That includes fill factor losses.
